"""Add inspection_cycle_time to ACModel

Revision ID: 2ea70d179271
Revises: dd9f99a2642e
Create Date: 2025-10-27 13:00:01.085761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea70d179271'
down_revision = 'dd9f99a2642e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_models', sa.Column('inspection_cycle_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ac_models', 'inspection_cycle_time')
    # ### end Alembic commands ###
