"""Add inspection time to ACModel

Revision ID: 412ecdad13d2
Revises: 2ea70d179271
Create Date: 2025-10-28 09:18:09.495171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ecdad13d2'
down_revision = '2ea70d179271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
